mosquitto_port: 1884
broadcast_port: 50001
broadcast_mask: "255.255.255.255"
peer_ip: "172.31.1.143"

mode: "gossip" # "federated" 
central_server: "172.31.1.143"

routing_topology:
  aggregation_topology: [0]
  pipeline_topology: [1]