param_grid:
  min_samples_leaf: [1, 2, 4, 5]
  n_estimators: [50, 100, 200, 500]
  max_depth: [10, 20, 50] # null -> torna-se None em Python



# GRELHA DE TESTE PARA O AGGREGATION.ipynb

# param_grid:
#   min_samples_leaf: 4
#   n_estimators: 100
#   max_depth: 100 # null -> torna-se None em Python